#ifndef SPS_SPS_HH
#define SPS_SPS_HH

#define SPS_COMMAND_FATAL_ERROR -1
#define SPS_COMMAND_SUCCESSFUL 0
#define SPS_COMMAND_UNEXPECTED_BEHAVIOUR 1

#define SPS_COMMAND_CONFIG_W_SPS 1
#define SPS_COMMAND_CONFIG_WO_SPS 2

#endif
